# AI & ML Course with BinX — Week 1 — Day 3 —  NumPy: Numerical Computing 

## 3.1  Why NumPy


Import numpy and print version

In [3]:
import numpy as np
print(np.__version__)

2.5.1


## 3.2 Creating Arrays

In [9]:
numbers = np.array([1, 2, 3, 4, 5])
print(numbers)
zero = np.zeros((1, 2))
ones = np.ones((3))
print(zero)
print(ones)
arange = np.arange (0, 10, 2)
linspaces = np.linspace(0, 1, 5)
print(arange)
print(linspaces)
random = np.random.rand(3, 3)
print(random) 

[1 2 3 4 5]
[[0. 0.]]
[1. 1. 1.]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.12761783 0.13609462 0.16948618]
 [0.35757626 0.18596625 0.95600274]
 [0.10303944 0.66884669 0.71146105]]


## 3.3 Array Attributes, Indexing & Slicing

In [14]:
m = np.array([[1, 2, 3], [4, 5, 6]])
print(m.shape)     
print(m.dtype)      
print(m.ndim)      
print(m[0, 2]) 
print(m[1, 1]) 
print(m[:, 1])      
print(m[1, :])  


(2, 3)
int64
2
3
5
[2 5]
[4 5 6]


## 3.4 Vectorized Operations

In [17]:
a  = np.array([1, 2, 3, 4])
print(a * 2)         
print(a + a) 
print(a.mean()) 
print(a[a > 2]) 

[2 4 6 8]
[2 4 6 8]
2.5
[3 4]


## 3.5 Broadcasting

In [18]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
row    = np.array([10, 20, 30])
print(matrix + row) 

[[11 22 33]
 [14 25 36]]


#  Hands-On Lab: NumPy Array Manipulation


Step 1: Create a 2D array (4,4) with values 1-16, print shape and dtype

In [20]:
numbers = np.arange(1, 17).reshape(4, 4)

print("My 4x4 array:")
print(numbers)
print("\nShape:", numbers.shape)
print("Data type:", numbers.dtype)

My 4x4 array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Shape: (4, 4)
Data type: int64


Step 2: Use slicing to extract second column and last row


In [21]:
second_column = numbers[:, 1]
last_row = numbers[-1, :]
print("Second column:", second_column)
print("Last row:", last_row)

Second column: [ 2  6 10 14]
Last row: [13 14 15 16]


Step 3: Use boolean mask to select values greater than the array's mean

In [22]:
average = numbers.mean()
above_average = numbers[numbers > average]
print("Average value:", average)
print("Values greater than average:", above_average)

Average value: 8.5
Values greater than average: [ 9 10 11 12 13 14 15 16]


Step 4: Add a 1D row to every row of a 2D array using broadcasting

In [23]:
extra_row = np.array([10, 20, 30, 40])
result = numbers + extra_row
print("Original array:")
print(numbers)
print("\nRow to add:", extra_row)
print("\nResult after broadcasting:")
print(result)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Row to add: [10 20 30 40]

Result after broadcasting:
[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]
 [23 34 45 56]]
