<div style="background-color:#2E0A24; border-left:7px solid #D946EF; padding:20px; border-radius:14px;">
<h1 style="color:#FFFFFF; font-size:30px; text-shadow:0 0 6px #D946EF; margin:0;">
🧪 Hands-On Lab: NumPy Array Manipulation
</h1>
</div>

<div style="background-color:#241827; border:1px solid #A855F7; border-left:5px solid #D946EF; padding:16px 20px; border-radius:11px; box-shadow:0 4px 14px rgba(0,0,0,0.25);">

<h3 style="color:#E9D5FF; font-size:21px; text-shadow:0 0 5px rgba(217,70,239,0.25); margin:0; letter-spacing:0.2px;">
Step 1: Create a 2D array (4×4) with values 1-16, print shape and dtype
</h3>

</div>

In [1]:
import numpy as np
print("\033[95mNumPy version:\033[0m", np.__version__)

NumPy version: 2.5.1


In [2]:
numbers = np.arange(1, 17).reshape(4, 4)

print("\033[95mMy 4x4 array:\033[0m")
print(numbers)
print("\n\033[94mShape:\033[0m", numbers.shape)
print("\033[92mData type:\033[0m", numbers.dtype)

My 4x4 array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Shape: (4, 4)
Data type: int64


<div style="background-color:#241827; border:1px solid #A855F7; border-left:5px solid #D946EF; padding:16px 20px; border-radius:11px; box-shadow:0 4px 14px rgba(0,0,0,0.25);">

<h3 style="color:#E9D5FF; font-size:21px; text-shadow:0 0 5px rgba(217,70,239,0.25); margin:0; letter-spacing:0.2px;">
Step 2: Use slicing to extract second column and last row
</h3>

</div>

In [3]:
second_column = numbers[:, 1]
last_row = numbers[-1, :]

print("\033[95mSecond column:\033[0m", second_column)
print("\033[94mLast row:\033[0m", last_row)

Second column: [ 2  6 10 14]
Last row: [13 14 15 16]


<div style="background-color:#241827; border:1px solid #A855F7; border-left:5px solid #D946EF; padding:16px 20px; border-radius:11px; box-shadow:0 4px 14px rgba(0,0,0,0.25);">

<h3 style="color:#E9D5FF; font-size:21px; text-shadow:0 0 5px rgba(217,70,239,0.25); margin:0; letter-spacing:0.2px;">
Step 3: Use boolean mask to select values greater than the array's mean
</h3>

</div>

In [4]:
average = numbers.mean()
above_average = numbers[numbers > average]

print("\033[93mAverage value:\033[0m", average)
print("\033[92mValues greater than average:\033[0m", above_average)

Average value: 8.5
Values greater than average: [ 9 10 11 12 13 14 15 16]


<div style="background-color:#241827; border:1px solid #A855F7; border-left:5px solid #D946EF; padding:16px 20px; border-radius:11px; box-shadow:0 4px 14px rgba(0,0,0,0.25);">

<h3 style="color:#E9D5FF; font-size:21px; text-shadow:0 0 5px rgba(217,70,239,0.25); margin:0; letter-spacing:0.2px;">
Step 4: Add a 1D row to every row of a 2D array using broadcasting
</h3>

</div>

In [5]:
extra_row = np.array([10, 20, 30, 40])
result = numbers + extra_row

print("\033[95mOriginal array:\033[0m")
print(numbers)
print("\n\033[94mRow to add:\033[0m", extra_row)
print("\n\033[92mResult after broadcasting:\033[0m")
print(result)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Row to add: [10 20 30 40]

Result after broadcasting:
[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]
 [23 34 45 56]]
