<div style="background-color:#2E0A24; border-left:7px solid #D946EF; padding:25px; border-radius:14px;">
<h1 style="color:#FFFFFF; font-size:34px; text-shadow:0 0 6px #D946EF; margin:0; border-bottom: 3px solid #D946EF; padding-bottom: 8px;">
AI & ML Course with BinX — Week 1 — Day 3 — NumPy: Numerical Computing
</h1>
</div>

<div style="background-color:#2E0A24; border-left:5px solid #D946EF; padding:15px 20px; border-radius:10px;">
<h2 style="color:#FFFFFF; font-size:24px; text-shadow:0 0 5px #D946EF; margin:0;">
3.1 Why NumPy
</h2>
<p style="color:#E8A8E0; font-size:16px; line-height:1.6;">
Import numpy and print the installed version.
</p>
</div>

In [1]:
import numpy as np
print("\033[95mNumPy version:\033[0m", np.__version__)

NumPy version: 2.5.1


<div style="background-color:#2E0A24; border-left:5px solid #D946EF; padding:15px 20px; border-radius:10px;">
<h2 style="color:#FFFFFF; font-size:24px; text-shadow:0 0 5px #D946EF; margin:0;">
3.2 Creating Arrays
</h2>
<p style="color:#E8A8E0; font-size:16px; line-height:1.6;">
NumPy gives me several ways to create arrays — from a Python list, filled
with zeros or ones, generated as a sequence, or filled with random
values. Each one is useful in a different situation.
</p>
</div>

In [2]:
# from a list
numbers = np.array([1, 2, 3, 4, 5])
print("\033[95mFrom a list:\033[0m", numbers)

# zeros and ones
zeros = np.zeros((1, 2))
ones = np.ones(3)
print("\033[94mZeros:\033[0m", zeros)
print("\033[92mOnes:\033[0m", ones)

# arange and linspace
arange_arr = np.arange(0, 10, 2)
linspace_arr = np.linspace(0, 1, 5)
print("\033[93mArange:\033[0m", arange_arr)
print("\033[96mLinspace:\033[0m", linspace_arr)

# random values
random_arr = np.random.rand(3, 3)
print("\033[95mRandom:\033[0m\n", random_arr)

From a list: [1 2 3 4 5]
Zeros: [[0. 0.]]
Ones: [1. 1. 1.]
Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Random:
 [[0.92066917 0.84223005 0.64815907]
 [0.20806869 0.62587938 0.69835793]
 [0.53874695 0.91586146 0.27745091]]


<div style="background-color:#2E0A24; border-left:5px solid #D946EF; padding:15px 20px; border-radius:10px;">
<h2 style="color:#FFFFFF; font-size:24px; text-shadow:0 0 5px #D946EF; margin:0;">
3.3 Array Attributes, Indexing & Slicing
</h2>
<p style="color:#E8A8E0; font-size:16px; line-height:1.6;">
Every array has attributes that describe it — its shape, data type, and
number of dimensions. I can also access specific elements or slices of
an array using indexing, the same way I would with a list, but extended
to work across multiple dimensions.
</p>
</div>

In [3]:
m = np.array([[1, 2, 3], [4, 5, 6]])

# attributes
print("\033[95mShape:\033[0m", m.shape)
print("\033[94mDtype:\033[0m", m.dtype)
print("\033[92mNdim:\033[0m", m.ndim)

# indexing
print("\033[93mElement [0, 2]:\033[0m", m[0, 2])
print("\033[96mElement [1, 1]:\033[0m", m[1, 1])

# slicing
print("\033[95mColumn 1 (all rows):\033[0m", m[:, 1])
print("\033[94mRow 1 (all columns):\033[0m", m[1, :])

Shape: (2, 3)
Dtype: int64
Ndim: 2
Element [0, 2]: 3
Element [1, 1]: 5
Column 1 (all rows): [2 5]
Row 1 (all columns): [4 5 6]


<div style="background-color:#2E0A24; border-left:5px solid #D946EF; padding:15px 20px; border-radius:10px;">
<h2 style="color:#FFFFFF; font-size:24px; text-shadow:0 0 5px #D946EF; margin:0;">
3.4 Vectorized Operations
</h2>
<p style="color:#E8A8E0; font-size:16px; line-height:1.6; margin-top:10px;">
Instead of looping through each element one by one, NumPy lets me apply
an operation to an entire array at once. This is called vectorization —
it's faster and much more readable than a manual loop, and it includes
boolean masking to filter values based on a condition.
</p>
</div>

In [4]:
a = np.array([1, 2, 3, 4])

print("\033[95mMultiplied by 2:\033[0m", a * 2)
print("\033[94mAdded to itself:\033[0m", a + a)
print("\033[92mMean:\033[0m", a.mean())
print("\033[93mValues greater than 2:\033[0m", a[a > 2])

Multiplied by 2: [2 4 6 8]
Added to itself: [2 4 6 8]
Mean: 2.5
Values greater than 2: [3 4]


<div style="background-color:#2E0A24; border-left:5px solid #D946EF; padding:15px 20px; border-radius:10px;">
<h2 style="color:#FFFFFF; font-size:24px; text-shadow:0 0 5px #D946EF; margin:0;">
3.5 Broadcasting
</h2>
<p style="color:#E8A8E0; font-size:16px; line-height:1.6; margin-top:10px;">
Broadcasting is how NumPy combines arrays of different shapes without
actually copying any data — for example, adding a single number to every
element, or adding a smaller array to every row of a bigger one. It's a
key concept because most shape-mismatch errors come from not
understanding how it works.
</p>
</div>

In [5]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
row = np.array([10, 20, 30])

print("\033[95mMatrix + row (broadcasted):\033[0m\n", matrix + row)

Matrix + row (broadcasted):
 [[11 22 33]
 [14 25 36]]
