<h1 style="color:#C39BD3; border-bottom: 3px solid #C39BD3; padding-bottom: 8px;">
AI & ML Course with BinX — Week 2 — Day 3 — Linear Algebra for ML 
</h1>

<blockquote style="border-left: 3px solid #FD1D1D; padding-left: 12px; margin-left: 0;">

🎨 **Notebook Design & Formatting Note**

I used ChatGPT as a design and formatting assistant to explore a new style for organizing my notebook.

I experimented with different Markdown layouts, colors, sections, and visual formatting to make the notebook more readable, organized, and enjoyable to review.

This was part of my learning process to improve not only my technical skills, but also my ability to document and present my work in a clearer way.

</blockquote>

## <span style="color:#F78BA0">3.1  Why Linear Algebra Is the Language of ML</span>

<blockquote style="border-left: 3px solid #FD1D1D; padding-left: 12px; margin-left: 0;"> Linear algebra is the foundation of machine learning because data and models are represented using vectors and matrices.

- A dataset is stored as a matrix.
- Each row represents one sample.
- Each column represents one feature.
- Model parameters are stored as vectors or matrices.
- Machine learning models perform matrix operations to make predictions and learn from data. </blockquote>

## <span style="color:#F78BA0">3.2 Vectors</span>

<blockquote style="border-left: 3px solid #FD1D1D; padding-left: 12px; margin-left: 0;">

A **vector** is an ordered list of numbers. In Machine Learning, a vector usually represents the **features of a single data sample**.

For example, a customer can be represented by three features:

- 🎂 Age
- 💰 Income
- 🗓️ Tenure

Each value in the vector corresponds to one feature.

</blockquote>

## <span style="color:#7E57C2">🎯 Goal</span>

<blockquote style="border-left: 3px solid #7E57C2; padding-left: 12px; margin-left: 0;">

In this section, we will learn how to represent a single data sample as a vector using NumPy.

</blockquote>

## <span style="color:#42A5F5">💻 Example</span>

<blockquote style="border-left: 3px solid #2196F3; padding-left: 12px; margin-left: 0;">

Let's create a vector representing one customer's features.

</blockquote>

In [10]:
import numpy as np

customer = np.array([25, 50000, 3])

print("\033[94mCustomer Vector:\033[0m", customer)

print("\033[92mAge:\033[0m", customer[0])
print("\033[93mIncome:\033[0m", customer[1])
print("\033[95mTenure:\033[0m", customer[2])

print("\033[91mVector Shape:\033[0m", customer.shape)

Customer Vector: [   25 50000     3]
Age: 25
Income: 50000
Tenure: 3
Vector Shape: (3,)


## <span style="color:#66BB6A">✅ Output Explanation</span>

<blockquote style="border-left: 3px solid #4CAF50; padding-left: 12px; margin-left: 0;">

The vector contains three features:

- 🎂 **25** → Age
- 💰 **50000** → Income
- 🗓️ **3** → Tenure

The shape **(3,)** means that the vector has three values.

</blockquote>

## <span style="color:#FF9800">💡 Note</span>

<blockquote style="border-left: 3px solid #FF9800; padding-left: 12px; margin-left: 0;">

A vector represents **one sample** in a dataset.

When we combine multiple vectors together, we get a **matrix** that represents the full dataset.

</blockquote>

## <span style="color:#F78BA0">3.3 Matrices</span>

<blockquote style="border-left: 3px solid #FD1D1D; padding-left: 12px; margin-left: 0;">

A **matrix** is a two-dimensional grid of numbers.

In Machine Learning, a matrix usually represents a **complete dataset**, where:

- 📌 Rows represent data samples.
- 📊 Columns represent features.

The shape of a matrix is written as:

**(rows, columns) = (samples, features)**

</blockquote>

## <span style="color:#7E57C2">🎯 Goal</span>

<blockquote style="border-left: 3px solid #7E57C2; padding-left: 12px; margin-left: 0;">

In this section, we will learn how to represent a complete dataset as a NumPy matrix and understand its shape.

</blockquote>

## <span style="color:#42A5F5">💻 Example</span>

<blockquote style="border-left: 3px solid #2196F3; padding-left: 12px; margin-left: 0;">

Let's create a dataset containing multiple customer samples.

Each row represents one customer, and each column represents one feature:

- 🎂 Age
- 💰 Income
- 🗓️ Tenure

</blockquote>

In [12]:
import numpy as np

customers = np.array([
    [25, 50000, 3],
    [40, 80000, 10],
    [33, 62000, 5]
])

print("\033[94mCustomer Dataset Matrix:\033[0m")
print(customers)

print("\n\033[92mMatrix Shape:\033[0m", customers.shape)

Customer Dataset Matrix:
[[   25 50000     3]
 [   40 80000    10]
 [   33 62000     5]]

Matrix Shape: (3, 3)


## <span style="color:#66BB6A">✅ Output Explanation</span>

<blockquote style="border-left: 3px solid #4CAF50; padding-left: 12px; margin-left: 0;">

The matrix contains **three customer samples**, and each sample has **three features**.

Rows represent:

- 👤 Customer 1
- 👤 Customer 2
- 👤 Customer 3

Columns represent:

- 🎂 Age
- 💰 Income
- 🗓️ Tenure

The shape **(3, 3)** means:

- 3 rows → 3 samples
- 3 columns → 3 features

</blockquote>

## <span style="color:#FF9800">💡 Note</span>

<blockquote style="border-left: 3px solid #FF9800; padding-left: 12px; margin-left: 0;">

In Machine Learning:

**One vector = one sample**

**Many vectors together = a matrix representing the dataset**

</blockquote>

## <span style="color:#F78BA0">3.4 The Dot Product</span>

<blockquote style="border-left: 3px solid #FD1D1D; padding-left: 12px; margin-left: 0;">

The **dot product** is an operation that multiplies two vectors element-by-element and then adds the results together.

In Machine Learning, the dot product is used to calculate predictions.

A linear model prediction is:

**Prediction = Features · Weights + Bias**

</blockquote>

## <span style="color:#7E57C2">🎯 Goal</span>

<blockquote style="border-left: 3px solid #7E57C2; padding-left: 12px; margin-left: 0;">

In this section, we will learn how the dot product combines features and weights to produce a prediction.

</blockquote>

## <span style="color:#42A5F5">💻 Example</span>

<blockquote style="border-left: 3px solid #2196F3; padding-left: 12px; margin-left: 0;">

Let's calculate a prediction using a feature vector and a weight vector.

Features represent the input data, while weights represent the importance of each feature.

</blockquote>

In [14]:
import numpy as np

features = np.array([25, 50000, 3])


weights = np.array([0.1, 0.0002, 1.5])

prediction = np.dot(features, weights)

print("\033[94mFeatures:\033[0m", features)
print("\033[92mWeights:\033[0m", weights)

print("\n\033[93mDot Product Prediction:\033[0m", prediction)

Features: [   25 50000     3]
Weights: [1.0e-01 2.0e-04 1.5e+00]

Dot Product Prediction: 17.0


## <span style="color:#66BB6A">✅ Output Explanation</span>

<blockquote style="border-left: 3px solid #4CAF50; padding-left: 12px; margin-left: 0;">

The dot product multiplies each feature by its corresponding weight and then sums the results:

\[
(25 \times 0.1) + (50000 \times 0.0002) + (3 \times 1.5)
\]

= 2.5 + 10 + 4.5

= **17.0**

The final value represents the model prediction before adding the bias.

</blockquote>

## <span style="color:#FF9800">💡 Note</span>

<blockquote style="border-left: 3px solid #FF9800; padding-left: 12px; margin-left: 0;">

The dot product is one of the most important operations in Machine Learning.

Models such as **Linear Regression** and **Logistic Regression** use this operation to generate predictions.

</blockquote>

## <span style="color:#F78BA0">3.5 Matrix Multiplication</span>

<blockquote style="border-left: 3px solid #FD1D1D; padding-left: 12px; margin-left: 0;">

Matrix multiplication applies the dot product across multiple samples at once.

In Machine Learning, this allows a model to make predictions for an entire dataset using a single operation.

The shape rule:

**(m × n) @ (n × p) = (m × p)**

The inner dimensions must match.

</blockquote>

## <span style="color:#7E57C2">🎯 Goal</span>

<blockquote style="border-left: 3px solid #7E57C2; padding-left: 12px; margin-left: 0;">

In this section, we will learn how matrix multiplication produces predictions for multiple samples and understand the importance of shapes.

</blockquote>

## <span style="color:#42A5F5">💻 Example</span>

<blockquote style="border-left: 3px solid #2196F3; padding-left: 12px; margin-left: 0;">

Let's use matrix multiplication to calculate predictions for multiple customers at once.

Each row represents one customer, and the weight vector represents the model parameters.

</blockquote>

In [15]:
import numpy as np

X = np.array([
    [25, 50000, 3],
    [40, 80000, 10]
])

weights = np.array([0.1, 0.0002, 1.5])

predictions = X @ weights

print("\033[94mInput Matrix X:\033[0m")
print(X)

print("\n\033[92mWeights Vector:\033[0m")
print(weights)

print("\n\033[93mPredictions:\033[0m")
print(predictions)

print("\n\033[95mPrediction Shape:\033[0m", predictions.shape)

Input Matrix X:
[[   25 50000     3]
 [   40 80000    10]]

Weights Vector:
[1.0e-01 2.0e-04 1.5e+00]

Predictions:
[17. 35.]

Prediction Shape: (2,)


## <span style="color:#66BB6A">✅ Output Explanation</span>

<blockquote style="border-left: 3px solid #4CAF50; padding-left: 12px; margin-left: 0;">

The matrix multiplication applies the dot product between each row in **X** and the weights vector.

For each customer, the model calculates one prediction:

- 👤 Customer 1 → Prediction
- 👤 Customer 2 → Prediction

The output shape is:

**(2,)**

which means we have two predictions, one for each sample.

</blockquote>

## <span style="color:#FF9800">💡 Shape Rule</span>

<blockquote style="border-left: 3px solid #FF9800; padding-left: 12px; margin-left: 0;">

For matrix multiplication:

**(m × n) @ (n × p) = (m × p)**

The two middle dimensions must be equal.

Example:

**(2 × 3) @ (3 × 1) = (2 × 1)**

The result contains one prediction for each sample.

</blockquote>

## <span style="color:#EF5350">🧠 Key Takeaway</span>

<blockquote style="border-left: 3px solid #E53935; padding-left: 12px; margin-left: 0;">

📌 In Machine Learning:

- Vector → One sample.
- Matrix → Full dataset.
- Dot Product → Prediction for one sample.
- Matrix Multiplication → Predictions for many samples at once.

Understanding shapes prevents many ML coding errors.

</blockquote>

## <span style="color:#EF5350">🧠 Key Takeaway</span>

<blockquote style="border-left: 3px solid #E53935; padding-left: 12px; margin-left: 0;">

📌 In Machine Learning:

- Vector → One sample.
- Matrix → Full dataset.
- Dot Product → Prediction for one sample.
- Matrix Multiplication → Predictions for many samples at once.

Understanding shapes prevents many ML coding errors.

</blockquote>

# <span style="color:#F78BA0">🧪 Hands-On Lab: Vectors, Matrices & Predictions</span>

<blockquote style="border-left: 3px solid #FD1D1D; padding-left: 12px; margin-left: 0;">

In this lab, we will apply linear algebra concepts using NumPy.

We will practice:

- Creating vectors and matrices.
- Computing dot products.
- Performing matrix multiplication.
- Understanding shape mismatch errors.

</blockquote>

## <span style="color:#42A5F5">🔹 Step 1: Create a Dataset Matrix</span>

<blockquote style="border-left: 3px solid #2196F3; padding-left: 12px; margin-left: 0;">

Create a matrix representing three samples.

Each row represents one sample, and each column represents one feature.

Features:

- 🎂 Age
- 💰 Income
- 🗓️ Tenure


</blockquote>

In [16]:
import numpy as np

X = np.array([
    [25, 50000, 3],
    [40, 80000, 10],
    [33, 62000, 5]
])

print("\033[94mDataset Matrix:\033[0m")
print(X)

print("\n\033[92mMatrix Shape:\033[0m", X.shape)

Dataset Matrix:
[[   25 50000     3]
 [   40 80000    10]
 [   33 62000     5]]

Matrix Shape: (3, 3)


## <span style="color:#66BB6A">✅ Explanation</span>

<blockquote style="border-left: 3px solid #4CAF50; padding-left: 12px; margin-left: 0;">

The matrix shape is **(3, 3)**:

- 3 rows → 3 samples
- 3 columns → 3 features

This matrix represents the complete dataset.

</blockquote>

## <span style="color:#42A5F5">🔹 Step 2: Dot Product Calculation</span>

<blockquote style="border-left: 3px solid #2196F3; padding-left: 12px; margin-left: 0;">

Calculate the dot product between one sample vector and a weight vector.

Then compare the manual calculation with NumPy.

</blockquote>

In [18]:
sample = X[0]

weights = np.array([0.1, 0.0002, 1.5])


manual_result = (
    sample[0] * weights[0] +
    sample[1] * weights[1] +
    sample[2] * weights[2]
)

numpy_result = np.dot(sample, weights)


print("\033[93mManual Dot Product:\033[0m", manual_result)
print("\033[92mNumPy Dot Product:\033[0m", numpy_result)

Manual Dot Product: 17.0
NumPy Dot Product: 17.0


## <span style="color:#66BB6A">✅ Explanation</span>

<blockquote style="border-left: 3px solid #4CAF50; padding-left: 12px; margin-left: 0;">

Both calculations should return the same value.

This confirms that NumPy's **dot()** performs:

Feature values × Weights → Sum → Prediction

</blockquote>

## <span style="color:#42A5F5">🔹 Step 3: Matrix Multiplication</span>

<blockquote style="border-left: 3px solid #2196F3; padding-left: 12px; margin-left: 0;">

Use matrix multiplication to calculate predictions for all samples at once.

Instead of calculating one sample at a time, the model can process the whole dataset using one operation.

</blockquote>

In [19]:
weights = np.array([0.1, 0.0002, 1.5])

predictions = X @ weights


print("\033[94mDataset Matrix:\033[0m")
print(X)

print("\n\033[93mWeights:\033[0m")
print(weights)

print("\n\033[92mPredictions:\033[0m")
print(predictions)

print("\n\033[95mPrediction Shape:\033[0m", predictions.shape)

Dataset Matrix:
[[   25 50000     3]
 [   40 80000    10]
 [   33 62000     5]]

Weights:
[1.0e-01 2.0e-04 1.5e+00]

Predictions:
[17.  35.  23.2]

Prediction Shape: (3,)


## <span style="color:#66BB6A">✅ Explanation</span>

<blockquote style="border-left: 3px solid #4CAF50; padding-left: 12px; margin-left: 0;">

The **@ operator** performs matrix multiplication.

Each row in the dataset is multiplied with the weights vector to produce one prediction.

The result:

- 👤 Sample 1 → Prediction 1
- 👤 Sample 2 → Prediction 2
- 👤 Sample 3 → Prediction 3

The output shape **(3,)** means we have three predictions.

</blockquote>

## <span style="color:#42A5F5">🔹 Step 4: Shape Mismatch Error</span>

<blockquote style="border-left: 3px solid #2196F3; padding-left: 12px; margin-left: 0;">

Machine Learning errors often happen because matrix shapes do not match.

Let's create an incorrect weight vector and observe the error.

</blockquote>

In [21]:
wrong_weights = np.array([0.1, 0.0002])

wrong_prediction = X @ wrong_weights

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

## <span style="color:#66BB6A">✅ Error Explanation</span>

<blockquote style="border-left: 3px solid #4CAF50; padding-left: 12px; margin-left: 0;">

The error happened because the shapes do not match.

The dataset matrix has shape:

**(3, 3)**

meaning:

- 3 samples
- 3 features

But the weight vector has shape:

**(2,)**

meaning:

- Only 2 weights

The number of features must equal the number of weights.

Correct:

**(3, 3) @ (3,) → (3,)**

</blockquote>