<div style="background:linear-gradient(135deg,#0F172A,#0C4A6E); padding:24px 26px; border-radius:16px; border:1px solid #06B6D4; box-shadow:0 0 16px rgba(6,182,212,0.14);">

<div style="font-size:14px; color:#67E8F9; letter-spacing:1px; margin-bottom:8px;">
🧮 LINEAR ALGEBRA FOR ML
</div>

<h2 style="color:#F8FAFC; font-size:28px; margin:0 0 14px 0; line-height:1.35;">
🧪 Hands-On Lab: <span style="color:#22D3EE;">Vectors, Matrices & Predictions</span>
</h2>

<div style="height:3px; width:90px; background:#F59E0B; border-radius:5px; margin-bottom:16px;"></div>

<p style="color:#CBD5E1; font-size:15px; line-height:1.7; margin:0 0 10px 0;">
In this lab, we will apply <b style="color:#FBBF24;">linear algebra concepts</b>
using NumPy.
</p>

<p style="color:#94A3B8; font-size:14px; margin:0 0 8px 0;">
We will practice:
</p>

<ul style="color:#CBD5E1; line-height:1.9; margin:0;">
<li>🔹 Creating vectors and matrices.</li>
<li>🔹 Computing dot products.</li>
<li>🔹 Performing matrix multiplication.</li>
<li>🔹 Understanding shape mismatch errors.</li>
</ul>

</div>

<div style="background:#0F172A; border-left:5px solid #06B6D4; padding:18px 22px; border-radius:12px; box-shadow:0 0 12px rgba(6,182,212,0.12);">

<h3 style="color:#22D3EE; margin:0 0 10px 0;">
🔹 Step 1: Create a Dataset Matrix
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 8px 0;">
Create a matrix representing <b style="color:#FBBF24;">three samples</b>.
</p>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 8px 0;">
Each <b style="color:#67E8F9;">row</b> represents one sample,
and each <b style="color:#67E8F9;">column</b> represents one feature.
</p>

<div style="background:#111827; border-radius:9px; padding:12px 16px; margin-top:12px;">

<p style="color:#94A3B8; margin:0 0 6px 0; font-size:14px;">
📊 Features
</p>

<ul style="color:#CBD5E1; line-height:1.8; margin:0;">
<li>🎂 <b style="color:#22D3EE;">Age</b></li>
<li>💰 <b style="color:#FBBF24;">Income</b></li>
<li>🗓️ <b style="color:#34D399;">Tenure</b></li>
</ul>

</div>

</div>

In [1]:
import numpy as np

X = np.array([
    [25, 50000, 3],
    [40, 80000, 10],
    [33, 62000, 5]
])

print("\033[94mDataset Matrix:\033[0m")
print(X)

print("\n\033[92mMatrix Shape:\033[0m", X.shape)

Dataset Matrix:
[[   25 50000     3]
 [   40 80000    10]
 [   33 62000     5]]

Matrix Shape: (3, 3)


<div style="background:linear-gradient(135deg,#0F172A,#0C4A6E); padding:18px 22px; border-radius:14px; border-left:5px solid #10B981; box-shadow:0 0 14px rgba(16,185,129,0.12);">

<h3 style="color:#34D399; margin:0 0 12px 0;">
✅ Explanation
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 10px 0;">
The matrix shape is <b style="color:#FBBF24; font-size:17px;">(3, 3)</b>:
</p>

<ul style="color:#CBD5E1; line-height:1.9; margin:0;">
<li><b style="color:#22D3EE;">3 rows</b> → 3 samples</li>
<li><b style="color:#67E8F9;">3 columns</b> → 3 features</li>
</ul>

<div style="background:#111827; border-left:4px solid #F59E0B; padding:12px 16px; border-radius:8px; margin-top:12px;">
<p style="color:#E2E8F0; margin:0; line-height:1.7;">
📊 This matrix represents the <b style="color:#FBBF24;">complete dataset</b>.
</p>
</div>

</div>

<div style="background:#0F172A; border-left:5px solid #06B6D4; padding:18px 22px; border-radius:12px; box-shadow:0 0 12px rgba(6,182,212,0.12);">

<h3 style="color:#22D3EE; margin:0 0 10px 0;">
🔹 Step 2: Dot Product Calculation
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 8px 0;">
Calculate the <b style="color:#67E8F9;">dot product</b> between one sample
vector and a weight vector.
</p>

<p style="color:#CBD5E1; line-height:1.7; margin:0;">
Then compare the <b style="color:#FBBF24;">manual calculation</b> with the
<b style="color:#34D399;">NumPy result</b>.
</p>

</div>

In [2]:
sample = X[0]

weights = np.array([0.1, 0.0002, 1.5])


manual_result = (
    sample[0] * weights[0] +
    sample[1] * weights[1] +
    sample[2] * weights[2]
)

numpy_result = np.dot(sample, weights)


print("\033[93mManual Dot Product:\033[0m", manual_result)
print("\033[92mNumPy Dot Product:\033[0m", numpy_result)

Manual Dot Product: 17.0
NumPy Dot Product: 17.0


<div style="background:#0F172A; border-left:5px solid #10B981; padding:18px 22px; border-radius:12px; box-shadow:0 0 12px rgba(16,185,129,0.12);">

<h3 style="color:#34D399; margin:0 0 10px 0;">
✅ Explanation
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 10px 0;">
Both calculations should return the <b style="color:#FBBF24;">same value</b>.
</p>

<p style="color:#CBD5E1; line-height:1.7; margin:0;">
This confirms that NumPy's <b style="color:#22D3EE;">dot()</b> performs:
</p>

<div style="background:#111827; border-left:4px solid #06B6D4; padding:12px 16px; border-radius:8px; margin-top:10px;">
<p style="color:#F8FAFC; margin:0; font-weight:bold;">
Feature values × Weights → Sum → <span style="color:#34D399;">Prediction</span>
</p>
</div>

</div>

<div style="background:linear-gradient(135deg,#0F172A,#0C4A6E); padding:20px 24px; border-radius:14px; border-left:5px solid #06B6D4; box-shadow:0 0 14px rgba(6,182,212,0.12); margin-top:18px;">

<h3 style="color:#22D3EE; margin:0 0 10px 0;">
🔹 Step 3: Matrix Multiplication
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0;">
Use <b style="color:#67E8F9;">matrix multiplication</b> to calculate
<b style="color:#F59E0B;">predictions for all samples at once</b>.
</p>

<p style="color:#CBD5E1; line-height:1.7; margin:8px 0 0 0;">
Instead of calculating one sample at a time, the model can process the
<b style="color:#34D399;">whole dataset using one operation</b>.
</p>

</div>

In [3]:
weights = np.array([0.1, 0.0002, 1.5])

predictions = X @ weights


print("\033[94mDataset Matrix:\033[0m")
print(X)

print("\n\033[93mWeights:\033[0m")
print(weights)

print("\n\033[92mPredictions:\033[0m")
print(predictions)

print("\n\033[95mPrediction Shape:\033[0m", predictions.shape)

Dataset Matrix:
[[   25 50000     3]
 [   40 80000    10]
 [   33 62000     5]]

Weights:
[1.0e-01 2.0e-04 1.5e+00]

Predictions:
[17.  35.  23.2]

Prediction Shape: (3,)


<div style="background:linear-gradient(135deg,#0F172A,#0C4A6E); padding:20px 24px; border-radius:14px; border-left:5px solid #10B981; box-shadow:0 0 14px rgba(16,185,129,0.12);">

<h3 style="color:#34D399; margin:0 0 12px 0;">
✅ Explanation
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 10px 0;">
The <b style="color:#22D3EE;">@ operator</b> performs matrix multiplication.
</p>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 8px 0;">
Each row in the dataset is multiplied with the
<b style="color:#FBBF24;">weights vector</b> to produce one prediction.
</p>

<ul style="color:#CBD5E1; line-height:1.9; margin-top:8px;">
<li>👤 <b style="color:#22D3EE;">Sample 1</b> → Prediction 1</li>
<li>👤 <b style="color:#22D3EE;">Sample 2</b> → Prediction 2</li>
<li>👤 <b style="color:#22D3EE;">Sample 3</b> → Prediction 3</li>
</ul>

<div style="background:#111827; border-left:4px solid #F59E0B; padding:12px 16px; border-radius:8px; margin-top:12px;">

<p style="color:#E2E8F0; margin:0; line-height:1.7;">
The output shape <b style="color:#FBBF24; font-size:17px;">(3,)</b>
means we have <b style="color:#34D399;">three predictions</b>.
</p>

</div>

</div>

<div style="background:#0F172A; border-left:5px solid #EF4444; padding:18px 22px; border-radius:12px; box-shadow:0 0 12px rgba(239,68,68,0.12); margin-top:18px;">

<h3 style="color:#F87171; margin:0 0 10px 0;">
🔹 Step 4: Shape Mismatch Error
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0;">
Machine Learning errors often happen because
<b style="color:#FBBF24;">matrix shapes do not match</b>.
</p>

<p style="color:#CBD5E1; line-height:1.7; margin:8px 0 0 0;">
Let's create an <b style="color:#F87171;">incorrect weight vector</b>
and observe the resulting error.
</p>

</div>

In [6]:
wrong_weights = np.array([0.1, 0.0002])

try:
    wrong_prediction = X @ wrong_weights
except ValueError as e:
    print("❌ Error:", e)

❌ Error: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)


<div style="background:#0F172A; border-left:5px solid #EF4444; padding:20px 22px; border-radius:12px; box-shadow:0 0 12px rgba(239,68,68,0.12);">

<h3 style="color:#F87171; margin:0 0 12px 0;">
⚠️ Shape Mismatch Error
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 12px 0;">
The error happened because the <b style="color:#F87171;">shapes do not match</b>.
The weight vector contains only <b style="color:#F87171;">2 values</b>,
while the input matrix <b style="color:#22D3EE;">X</b> contains
<b style="color:#34D399;">3 features per sample</b>.
</p>

<div style="background:#111827; border-radius:9px; padding:12px 16px; margin:10px 0;">

<p style="color:#CBD5E1; margin:0; line-height:1.8;">
<b style="color:#67E8F9;">X shape:</b> (3, 3)
<br>
<span style="color:#94A3B8;">→ 3 samples</span>
<br>
<span style="color:#94A3B8;">→ 3 features</span>
<br><br>
<b style="color:#FBBF24;">Weights shape:</b> (2,)
<br>
<span style="color:#94A3B8;">→ Only 2 weights</span>
</p>

</div>

<p style="color:#CBD5E1; line-height:1.7; margin:12px 0 10px 0;">
For matrix multiplication, the number of
<b style="color:#67E8F9;">features must equal the number of weights</b>.
Since <b style="color:#F87171;">3 ≠ 2</b>, NumPy raises a
<b style="color:#F87171;">ValueError</b>.
</p>

<div style="background:#111827; border-left:4px solid #10B981; padding:12px 16px; border-radius:8px;">

<p style="color:#94A3B8; margin:0 0 6px 0;">
✔️ Correct:
</p>

<p style="color:#F8FAFC; font-size:18px; font-weight:bold; margin:0;">
(3, 3) @ (3,) → <span style="color:#34D399;">(3,)</span>
</p>

</div>

</div>