<div style="background:linear-gradient(135deg,#0F172A,#0C4A6E); padding:28px; border-radius:18px; border:1px solid #06B6D4; box-shadow:0 0 20px rgba(6,182,212,0.22);">

<div style="font-size:14px; color:#67E8F9; letter-spacing:2px; margin-bottom:10px;">
⚡ AI & ML COURSE WITH BINX
</div>

<h1 style="color:#F8FAFC; font-size:34px; margin:0; line-height:1.35;">
🔢 Week 2 — Day 3 <br>
<span style="color:#22D3EE;">Linear Algebra for ML</span>
</h1>

<div style="height:3px; width:100px; background:#F59E0B; margin-top:18px; border-radius:5px;"></div>

<p style="color:#CBD5E1; font-size:15px; margin:16px 0 0 0; line-height:1.6;">
Understanding vectors, matrices, and mathematical operations that power machine learning algorithms.
</p>

</div>

<div style="background:linear-gradient(135deg,#0F172A,#0C4A6E); padding:18px 22px; border-radius:14px; border-left:5px solid #06B6D4; box-shadow:0 0 14px rgba(6,182,212,0.15);">

<h4 style="color:#67E8F9; margin:0 0 10px 0;">
🎨 Notebook Design & Formatting Note
</h4>

<p style="color:#CBD5E1; margin:0; line-height:1.7;">
I used <b style="color:#22D3EE;">ChatGPT</b> as a design and formatting assistant
to explore a new style for organizing my notebook.
I experimented with different <b style="color:#F59E0B;">Markdown layouts, colors,
sections, and visual formatting</b> to make the notebook more readable,
organized, and enjoyable to review.
</p>

<p style="color:#CBD5E1; margin:10px 0 0 0; line-height:1.7;">
This was part of my learning process to improve not only my
<b style="color:#22D3EE;">technical skills</b>, but also my ability to document
and present my work in a clearer and more structured way.
</p>

</div>

<div style="background:#0F172A; border:1px solid #06B6D4; border-radius:14px; padding:20px 24px; box-shadow:0 0 12px rgba(6,182,212,0.12);">

<h3 style="color:#22D3EE; margin:0 0 14px 0;">
📐 3.1 Why Linear Algebra Is the Language of ML
</h3>

<ul style="color:#CBD5E1; line-height:1.9; margin:0; padding-left:22px;">

<li>
A dataset is stored as a <b style="color:#F59E0B;">matrix</b>.
</li>

<li>
Each row represents one <b style="color:#22D3EE;">sample</b>.
</li>

<li>
Each column represents one <b style="color:#22D3EE;">feature</b>.
</li>

<li>
Model parameters are stored as <b style="color:#F59E0B;">vectors or matrices</b>.
</li>

<li>
Machine learning models perform <b style="color:#67E8F9;">matrix operations</b>
to make predictions and learn from data.
</li>

</ul>

</div>

<div style="background:#0F172A; border:1px solid #06B6D4; border-radius:14px; padding:20px 24px; box-shadow:0 0 12px rgba(6,182,212,0.12);">

<h3 style="color:#22D3EE; margin:0 0 14px 0;">
🧩 3.2 Vectors
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 12px 0;">
A <b style="color:#67E8F9;">vector</b> is an ordered list of numbers.
In Machine Learning, a vector usually represents the
<b style="color:#F59E0B;">features of a single data sample</b>.
</p>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 8px 0;">
For example, a customer can be represented by three features:
</p>

<ul style="color:#CBD5E1; line-height:1.9; margin-top:0;">
<li>🎂 <b style="color:#22D3EE;">Age</b></li>
<li>💰 <b style="color:#22D3EE;">Income</b></li>
<li>🗓️ <b style="color:#22D3EE;">Tenure</b></li>
</ul>

<p style="color:#CBD5E1; line-height:1.7; margin:0;">
Each value in the vector corresponds to one
<b style="color:#F59E0B;">feature</b>.
</p>

</div>

<div style="background:linear-gradient(135deg,#0F172A,#0C4A6E); padding:18px 22px; border-radius:14px; border-left:5px solid #F59E0B; box-shadow:0 0 14px rgba(245,158,11,0.12);">

<h3 style="color:#FBBF24; margin:0 0 8px 0;">
🎯 Goal
</h3>

<p style="color:#CBD5E1; margin:0; line-height:1.7;">
In this section, we will learn how to represent a
<b style="color:#22D3EE;">single data sample as a vector</b>
using <b style="color:#67E8F9;">NumPy</b>.
</p>

</div>

<div style="background:#0F172A; border:1px solid #06B6D4; border-radius:14px; padding:18px 22px; box-shadow:0 0 12px rgba(6,182,212,0.12);">

<h3 style="color:#22D3EE; margin:0 0 8px 0;">
💻 Example
</h3>

<p style="color:#CBD5E1; margin:0; line-height:1.7;">
Let's create a <b style="color:#F59E0B;">vector</b> representing one customer's features.
</p>

</div>

In [1]:
import numpy as np

customer = np.array([25, 50000, 3])

print("\033[94mCustomer Vector:\033[0m", customer)

print("\033[92mAge:\033[0m", customer[0])
print("\033[93mIncome:\033[0m", customer[1])
print("\033[95mTenure:\033[0m", customer[2])

print("\033[91mVector Shape:\033[0m", customer.shape)

Customer Vector: [   25 50000     3]
Age: 25
Income: 50000
Tenure: 3
Vector Shape: (3,)


<div style="background:linear-gradient(135deg,#0F172A,#0C4A6E); padding:18px 22px; border-radius:14px; border-left:5px solid #10B981; box-shadow:0 0 14px rgba(16,185,129,0.12);">

<h3 style="color:#34D399; margin:0 0 12px 0;">
✅ Output Explanation
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 10px 0;">
The vector contains three features:
</p>

<ul style="color:#CBD5E1; line-height:1.9; margin-top:0;">
<li>🎂 <b style="color:#22D3EE;">25</b> → Age</li>
<li>💰 <b style="color:#FBBF24;">50000</b> → Income</li>
<li>🗓️ <b style="color:#A78BFA;">3</b> → Tenure</li>
</ul>

<p style="color:#CBD5E1; line-height:1.7; margin:0;">
The shape <b style="color:#34D399;">(3,)</b> means that the vector contains
<b style="color:#22D3EE;">three values</b>, with each value representing one feature.
</p>

</div>

<div style="background:#0F172A; border:1px solid #06B6D4; border-radius:14px; padding:18px 22px; box-shadow:0 0 12px rgba(6,182,212,0.12);">

<h3 style="color:#FBBF24; margin:0 0 10px 0;">
💡 Note
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 8px 0;">
A <b style="color:#22D3EE;">vector</b> represents
<b style="color:#F8FAFC;">one sample</b> in a dataset.
</p>

<p style="color:#CBD5E1; line-height:1.7; margin:0;">
When we combine multiple vectors together, we get a
<b style="color:#67E8F9;">matrix</b> that represents the
<b style="color:#F8FAFC;">full dataset</b>.
</p>

</div>

<div style="background:linear-gradient(135deg,#0F172A,#0C4A6E); padding:20px 24px; border-radius:14px; border-left:5px solid #06B6D4; box-shadow:0 0 14px rgba(6,182,212,0.12);">

<h3 style="color:#22D3EE; margin:0 0 12px 0;">
🧮 3.3 Matrices
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 10px 0;">
A <b style="color:#67E8F9;">matrix</b> is a two-dimensional grid of numbers.
</p>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 8px 0;">
In Machine Learning, a matrix usually represents a
<b style="color:#F59E0B;">complete dataset</b>, where:
</p>

<ul style="color:#CBD5E1; line-height:1.9; margin-top:0;">
<li>📌 <b style="color:#22D3EE;">Rows</b> represent data samples.</li>
<li>📊 <b style="color:#22D3EE;">Columns</b> represent features.</li>
</ul>

<div style="background:#111827; border-left:4px solid #F59E0B; padding:12px 16px; border-radius:8px; margin-top:14px;">

<p style="color:#E2E8F0; margin:0; line-height:1.6;">
The shape of a matrix is written as:
<br>
<b style="color:#FBBF24; font-size:16px;">
(rows, columns) = (samples, features)
</b>
</p>

</div>

</div>

<div style="background:#0F172A; border:1px solid #06B6D4; border-radius:14px; padding:18px 22px; box-shadow:0 0 12px rgba(6,182,212,0.12);">

<h3 style="color:#FBBF24; margin:0 0 8px 0;">
🎯 Goal
</h3>

<p style="color:#CBD5E1; margin:0; line-height:1.7;">
In this section, we will learn how to represent a
<b style="color:#22D3EE;">complete dataset as a NumPy matrix</b>
and understand its <b style="color:#67E8F9;">shape</b>.
</p>

</div>

<div style="background:linear-gradient(135deg,#0F172A,#0C4A6E); padding:20px 24px; border-radius:14px; border-left:5px solid #06B6D4; box-shadow:0 0 14px rgba(6,182,212,0.12);">

<h3 style="color:#22D3EE; margin:0 0 12px 0;">
💻 Example
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 10px 0;">
Let's create a dataset containing multiple customer samples.
</p>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 8px 0;">
Each <b style="color:#F59E0B;">row</b> represents one customer,
and each <b style="color:#67E8F9;">column</b> represents one feature:
</p>

<ul style="color:#CBD5E1; line-height:1.9; margin:0;">
<li>🎂 <b style="color:#22D3EE;">Age</b></li>
<li>💰 <b style="color:#22D3EE;">Income</b></li>
<li>🗓️ <b style="color:#22D3EE;">Tenure</b></li>
</ul>

</div>

In [2]:
import numpy as np

customers = np.array([
    [25, 50000, 3],
    [40, 80000, 10],
    [33, 62000, 5]
])

print("\033[94mCustomer Dataset Matrix:\033[0m")
print(customers)

print("\n\033[92mMatrix Shape:\033[0m", customers.shape)

Customer Dataset Matrix:
[[   25 50000     3]
 [   40 80000    10]
 [   33 62000     5]]

Matrix Shape: (3, 3)


<div style="background:linear-gradient(135deg,#0F172A,#0C4A6E); padding:20px 24px; border-radius:14px; border-left:5px solid #10B981; box-shadow:0 0 14px rgba(16,185,129,0.12);">

<h3 style="color:#34D399; margin:0 0 12px 0;">
✅ Output Explanation
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 10px 0;">
The matrix contains <b style="color:#22D3EE;">three customer samples</b>,
and each sample has <b style="color:#FBBF24;">three features</b>.
</p>

<div style="background:#111827; border-radius:10px; padding:12px 16px; margin:10px 0;">

<p style="color:#67E8F9; margin:0 0 6px 0; font-weight:bold;">
Rows represent:
</p>

<ul style="color:#CBD5E1; line-height:1.8; margin:0;">
<li>👤 Customer 1</li>
<li>👤 Customer 2</li>
<li>👤 Customer 3</li>
</ul>

</div>

<div style="background:#111827; border-radius:10px; padding:12px 16px; margin:10px 0;">

<p style="color:#67E8F9; margin:0 0 6px 0; font-weight:bold;">
Columns represent:
</p>

<ul style="color:#CBD5E1; line-height:1.8; margin:0;">
<li>🎂 Age</li>
<li>💰 Income</li>
<li>🗓️ Tenure</li>
</ul>

</div>

<div style="background:#111827; border-left:4px solid #F59E0B; padding:12px 16px; border-radius:8px; margin-top:14px;">

<p style="color:#E2E8F0; margin:0; line-height:1.7;">
The shape <b style="color:#FBBF24;">(3, 3)</b> means:
<br>
<b style="color:#34D399;">3 rows</b> → 3 samples
<br>
<b style="color:#22D3EE;">3 columns</b> → 3 features
</p>

</div>

</div>

<div style="background:#0F172A; border:1px solid #06B6D4; border-radius:14px; padding:18px 22px; box-shadow:0 0 12px rgba(6,182,212,0.12);">

<h3 style="color:#FBBF24; margin:0 0 12px 0;">
💡 Note
</h3>

<div style="display:flex; flex-direction:column; gap:10px;">

<div style="background:#111827; border-left:4px solid #22D3EE; padding:12px 16px; border-radius:8px;">
<span style="color:#CBD5E1;">One vector</span>
<span style="color:#67E8F9; font-weight:bold;"> = one sample</span>
</div>

<div style="background:#111827; border-left:4px solid #10B981; padding:12px 16px; border-radius:8px;">
<span style="color:#CBD5E1;">Many vectors together</span>
<span style="color:#34D399; font-weight:bold;"> = a matrix representing the dataset</span>
</div>

</div>

</div>

<div style="background:linear-gradient(135deg,#0F172A,#0C4A6E); padding:20px 24px; border-radius:14px; border-left:5px solid #06B6D4; box-shadow:0 0 14px rgba(6,182,212,0.12);">

<h3 style="color:#22D3EE; margin:0 0 12px 0;">
🔢 3.4 The Dot Product
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 10px 0;">
The <b style="color:#67E8F9;">dot product</b> is an operation that multiplies
two vectors element-by-element and then adds the results together.
</p>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 12px 0;">
In Machine Learning, the dot product is used to
<b style="color:#F59E0B;">calculate predictions</b>.
</p>

<div style="background:#111827; border-left:4px solid #10B981; padding:14px 18px; border-radius:9px;">

<p style="color:#94A3B8; margin:0 0 6px 0; font-size:14px;">
A linear model prediction:
</p>

<p style="color:#F8FAFC; font-size:18px; margin:0; font-weight:bold;">
Prediction = <span style="color:#22D3EE;">Features · Weights</span>
+ <span style="color:#FBBF24;">Bias</span>
</p>

</div>

</div>

<div style="background:#0F172A; border:1px solid #06B6D4; border-radius:14px; padding:18px 22px; box-shadow:0 0 12px rgba(6,182,212,0.12);">

<h3 style="color:#FBBF24; margin:0 0 8px 0;">
🎯 Goal
</h3>

<p style="color:#CBD5E1; margin:0; line-height:1.7;">
In this section, we will learn how the
<b style="color:#22D3EE;">dot product</b> combines
<b style="color:#67E8F9;">features and weights</b> to produce a
<b style="color:#F59E0B;">prediction</b>.
</p>

</div>

<div style="background:linear-gradient(135deg,#0F172A,#0C4A6E); padding:20px 24px; border-radius:14px; border-left:5px solid #06B6D4; box-shadow:0 0 14px rgba(6,182,212,0.12);">

<h3 style="color:#22D3EE; margin:0 0 12px 0;">
💻 Example
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 8px 0;">
Let's calculate a <b style="color:#F59E0B;">prediction</b> using a feature vector
and a weight vector.
</p>

<p style="color:#CBD5E1; line-height:1.7; margin:0;">
<b style="color:#67E8F9;">Features</b> represent the input data, while
<b style="color:#FBBF24;">weights</b> represent the importance of each feature.
</p>

</div>

In [4]:
import numpy as np

features = np.array([25, 50000, 3])

weights = np.array([0.1, 0.0002, 1.5])

prediction = np.dot(features, weights)

print("\033[94mFeatures:\033[0m", features)
print("\033[92mWeights:\033[0m", weights)

print("\n\033[93mDot Product Prediction:\033[0m", prediction)

Features: [   25 50000     3]
Weights: [1.0e-01 2.0e-04 1.5e+00]

Dot Product Prediction: 17.0


<div style="background:linear-gradient(135deg,#0F172A,#0C4A6E); padding:20px 24px; border-radius:14px; border-left:5px solid #10B981; box-shadow:0 0 14px rgba(16,185,129,0.12);">

<h3 style="color:#34D399; margin:0 0 12px 0;">
✅ Output Explanation
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 10px 0;">
The dot product multiplies each feature by its corresponding weight and then
<b style="color:#22D3EE;">sums the results</b>:
</p>

<div style="background:#111827; border-left:4px solid #F59E0B; padding:14px 18px; border-radius:9px; margin:12px 0;">

<p style="color:#E2E8F0; margin:0; line-height:1.8; font-size:16px;">
(25 × 0.1) + (50000 × 0.0002) + (3 × 1.5)
<br>
= 2.5 + 10 + 4.5
<br>
= <b style="color:#FBBF24; font-size:18px;">17.0</b>
</p>

</div>

<p style="color:#CBD5E1; line-height:1.7; margin:0;">
The final value represents the
<b style="color:#34D399;">model prediction</b> before adding the bias.
</p>

</div>

<div style="background:#0F172A; border:1px solid #06B6D4; border-radius:14px; padding:18px 22px; box-shadow:0 0 12px rgba(6,182,212,0.12);">

<h3 style="color:#FBBF24; margin:0 0 10px 0;">
💡 Note
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 10px 0;">
The <b style="color:#22D3EE;">dot product</b> is one of the most important
operations in Machine Learning.
</p>

<p style="color:#CBD5E1; line-height:1.7; margin:0;">
Models such as <b style="color:#67E8F9;">Linear Regression</b> and
<b style="color:#A78BFA;">Logistic Regression</b> use this operation
to generate <b style="color:#F59E0B;">predictions</b>.
</p>

</div>

<div style="background:linear-gradient(135deg,#0F172A,#0C4A6E); padding:20px 24px; border-radius:14px; border-left:5px solid #06B6D4; box-shadow:0 0 14px rgba(6,182,212,0.12);">

<h3 style="color:#22D3EE; margin:0 0 12px 0;">
🧮 3.5 Matrix Multiplication
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 10px 0;">
Matrix multiplication applies the <b style="color:#67E8F9;">dot product</b>
across multiple samples at once.
</p>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 12px 0;">
In Machine Learning, this allows a model to make
<b style="color:#F59E0B;">predictions for an entire dataset</b>
using a single operation.
</p>

<div style="background:#111827; border-left:4px solid #10B981; padding:14px 18px; border-radius:9px; margin-top:12px;">

<p style="color:#94A3B8; margin:0 0 6px 0; font-size:14px;">
📐 Shape Rule
</p>

<p style="color:#F8FAFC; font-size:18px; margin:0; font-weight:bold;">
(m × n) @ (n × p) = <span style="color:#34D399;">(m × p)</span>
</p>

<p style="color:#CBD5E1; margin:10px 0 0 0; line-height:1.6;">
The <b style="color:#FBBF24;">inner dimensions must match</b>
for matrix multiplication to be valid.
</p>

</div>

</div>

<div style="background:#0F172A; border:1px solid #06B6D4; border-radius:14px; padding:18px 22px; box-shadow:0 0 12px rgba(6,182,212,0.12);">

<h3 style="color:#FBBF24; margin:0 0 8px 0;">
🎯 Goal
</h3>

<p style="color:#CBD5E1; margin:0; line-height:1.7;">
In this section, we will learn how
<b style="color:#22D3EE;">matrix multiplication</b> produces
<b style="color:#67E8F9;">predictions for multiple samples</b>
and understand the importance of
<b style="color:#F59E0B;">matrix shapes</b>.
</p>

</div>

<div style="background:linear-gradient(135deg,#0F172A,#0C4A6E); padding:20px 24px; border-radius:14px; border-left:5px solid #06B6D4; box-shadow:0 0 14px rgba(6,182,212,0.12);">

<h3 style="color:#22D3EE; margin:0 0 12px 0;">
💻 Example
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 8px 0;">
Let's use <b style="color:#67E8F9;">matrix multiplication</b> to calculate
<b style="color:#F59E0B;">predictions for multiple customers at once</b>.
</p>

<p style="color:#CBD5E1; line-height:1.7; margin:0;">
Each <b style="color:#22D3EE;">row</b> represents one customer, while the
<b style="color:#FBBF24;">weight vector</b> represents the model parameters.
</p>

</div>

In [5]:
import numpy as np

X = np.array([
    [25, 50000, 3],
    [40, 80000, 10]
])

weights = np.array([0.1, 0.0002, 1.5])

predictions = X @ weights

print("\033[94mInput Matrix X:\033[0m")
print(X)

print("\n\033[92mWeights Vector:\033[0m")
print(weights)

print("\n\033[93mPredictions:\033[0m")
print(predictions)

print("\n\033[95mPrediction Shape:\033[0m", predictions.shape)

Input Matrix X:
[[   25 50000     3]
 [   40 80000    10]]

Weights Vector:
[1.0e-01 2.0e-04 1.5e+00]

Predictions:
[17. 35.]

Prediction Shape: (2,)


<div style="background:linear-gradient(135deg,#0F172A,#0C4A6E); padding:20px 24px; border-radius:14px; border-left:5px solid #10B981; box-shadow:0 0 14px rgba(16,185,129,0.12);">

<h3 style="color:#34D399; margin:0 0 12px 0;">
✅ Output Explanation
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 10px 0;">
The matrix multiplication applies the <b style="color:#22D3EE;">dot product</b>
between each row in <b style="color:#67E8F9;">X</b> and the
<b style="color:#FBBF24;">weights vector</b>.
</p>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 8px 0;">
For each customer, the model calculates one prediction:
</p>

<ul style="color:#CBD5E1; line-height:1.9; margin-top:0;">
<li>👤 <b style="color:#22D3EE;">Customer 1</b> → Prediction</li>
<li>👤 <b style="color:#22D3EE;">Customer 2</b> → Prediction</li>
</ul>

<div style="background:#111827; border-left:4px solid #F59E0B; padding:12px 16px; border-radius:8px; margin-top:12px;">

<p style="color:#94A3B8; margin:0 0 6px 0;">
📐 Output Shape
</p>

<p style="color:#F8FAFC; margin:0; line-height:1.7;">
<b style="color:#FBBF24; font-size:18px;">(2,)</b>
<br>
This means there are <b style="color:#34D399;">two predictions</b>,
one for each sample.
</p>

</div>

</div>

<div style="background:#0F172A; border:1px solid #06B6D4; border-radius:14px; padding:18px 22px; box-shadow:0 0 12px rgba(6,182,212,0.12);">

<h3 style="color:#FBBF24; margin:0 0 12px 0;">
💡 Shape Rule
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 10px 0;">
For matrix multiplication:
</p>

<div style="background:#111827; border-left:4px solid #22D3EE; padding:12px 16px; border-radius:8px; margin:10px 0;">

<p style="color:#F8FAFC; font-size:18px; margin:0; font-weight:bold;">
(m × n) @ (n × p) = <span style="color:#34D399;">(m × p)</span>
</p>

</div>

<p style="color:#CBD5E1; line-height:1.7; margin:10px 0;">
The <b style="color:#F59E0B;">two middle dimensions must be equal</b>.
</p>

<p style="color:#67E8F9; font-weight:bold; margin:14px 0 6px 0;">
Example:
</p>

<div style="background:#111827; border-left:4px solid #10B981; padding:12px 16px; border-radius:8px;">

<p style="color:#F8FAFC; font-size:17px; margin:0; font-weight:bold;">
(2 × 3) @ (3 × 1) = <span style="color:#34D399;">(2 × 1)</span>
</p>

</div>

<p style="color:#CBD5E1; line-height:1.7; margin:12px 0 0 0;">
The result contains <b style="color:#FBBF24;">one prediction for each sample</b>.
</p>

</div>

<div style="background:linear-gradient(135deg,#0F172A,#0C4A6E); padding:20px 24px; border-radius:14px; border-left:5px solid #F59E0B; box-shadow:0 0 14px rgba(245,158,11,0.12);">

<h3 style="color:#FBBF24; margin:0 0 14px 0;">
🧠 Key Takeaway
</h3>

<p style="color:#CBD5E1; line-height:1.8; margin:0;">
📌 <b style="color:#22D3EE;">In Machine Learning:</b>
</p>

<ul style="color:#CBD5E1; line-height:2; margin-top:8px;">
<li><b style="color:#67E8F9;">Vector</b> → One sample.</li>
<li><b style="color:#34D399;">Matrix</b> → Full dataset.</li>
<li><b style="color:#A78BFA;">Dot Product</b> → Prediction for one sample.</li>
<li><b style="color:#F59E0B;">Matrix Multiplication</b> → Predictions for many samples at once.</li>
</ul>

<div style="background:#111827; border-left:4px solid #EF4444; padding:12px 16px; border-radius:8px; margin-top:14px;">

<p style="color:#E2E8F0; margin:0; line-height:1.7;">
💡 Understanding <b style="color:#FBBF24;">matrix shapes</b> is essential because
it helps prevent many <b style="color:#F87171;">ML coding errors</b>.
</p>

</div>

</div>

<div style="background:linear-gradient(135deg,#0F172A,#0C4A6E); padding:20px 24px; border-radius:14px; border-left:5px solid #F59E0B; box-shadow:0 0 14px rgba(245,158,11,0.12);">

<h3 style="color:#FBBF24; margin:0 0 14px 0;">
🧠 Key Takeaway
</h3>

<p style="color:#CBD5E1; line-height:1.8; margin:0 0 8px 0;">
📌 <b style="color:#22D3EE;">In Machine Learning:</b>
</p>

<ul style="color:#CBD5E1; line-height:2; margin-top:0;">
<li><b style="color:#67E8F9;">Vector</b> → One sample.</li>
<li><b style="color:#34D399;">Matrix</b> → Full dataset.</li>
<li><b style="color:#A78BFA;">Dot Product</b> → Prediction for one sample.</li>
<li><b style="color:#F59E0B;">Matrix Multiplication</b> → Predictions for many samples at once.</li>
</ul>

<div style="background:#111827; border-left:4px solid #EF4444; padding:12px 16px; border-radius:8px; margin-top:14px;">

<p style="color:#E2E8F0; margin:0; line-height:1.7;">
💡 Understanding <b style="color:#FBBF24;">shapes</b> prevents many
<b style="color:#F87171;">ML coding errors</b>.
</p>

</div>

</div>

<div style="background:linear-gradient(135deg,#0F172A,#0C4A6E); padding:24px 26px; border-radius:16px; border:1px solid #06B6D4; box-shadow:0 0 16px rgba(6,182,212,0.14);">

<div style="font-size:14px; color:#67E8F9; letter-spacing:1px; margin-bottom:8px;">
🧮 LINEAR ALGEBRA FOR ML
</div>

<h2 style="color:#F8FAFC; font-size:28px; margin:0 0 14px 0; line-height:1.35;">
🧪 Hands-On Lab: <span style="color:#22D3EE;">Vectors, Matrices & Predictions</span>
</h2>

<div style="height:3px; width:90px; background:#F59E0B; border-radius:5px; margin-bottom:16px;"></div>

<p style="color:#CBD5E1; font-size:15px; line-height:1.7; margin:0 0 10px 0;">
In this lab, we will apply <b style="color:#FBBF24;">linear algebra concepts</b>
using NumPy.
</p>

<p style="color:#94A3B8; font-size:14px; margin:0 0 8px 0;">
We will practice:
</p>

<ul style="color:#CBD5E1; line-height:1.9; margin:0;">
<li>🔹 Creating vectors and matrices.</li>
<li>🔹 Computing dot products.</li>
<li>🔹 Performing matrix multiplication.</li>
<li>🔹 Understanding shape mismatch errors.</li>
</ul>

</div>

<div style="background:#0F172A; border-left:5px solid #06B6D4; padding:18px 22px; border-radius:12px; box-shadow:0 0 12px rgba(6,182,212,0.12);">

<h3 style="color:#22D3EE; margin:0 0 10px 0;">
🔹 Step 1: Create a Dataset Matrix
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 8px 0;">
Create a matrix representing <b style="color:#FBBF24;">three samples</b>.
</p>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 8px 0;">
Each <b style="color:#67E8F9;">row</b> represents one sample,
and each <b style="color:#67E8F9;">column</b> represents one feature.
</p>

<div style="background:#111827; border-radius:9px; padding:12px 16px; margin-top:12px;">

<p style="color:#94A3B8; margin:0 0 6px 0; font-size:14px;">
📊 Features
</p>

<ul style="color:#CBD5E1; line-height:1.8; margin:0;">
<li>🎂 <b style="color:#22D3EE;">Age</b></li>
<li>💰 <b style="color:#FBBF24;">Income</b></li>
<li>🗓️ <b style="color:#34D399;">Tenure</b></li>
</ul>

</div>

</div>

In [6]:
import numpy as np

X = np.array([
    [25, 50000, 3],
    [40, 80000, 10],
    [33, 62000, 5]
])

print("\033[94mDataset Matrix:\033[0m")
print(X)

print("\n\033[92mMatrix Shape:\033[0m", X.shape)

Dataset Matrix:
[[   25 50000     3]
 [   40 80000    10]
 [   33 62000     5]]

Matrix Shape: (3, 3)


<div style="background:linear-gradient(135deg,#0F172A,#0C4A6E); padding:18px 22px; border-radius:14px; border-left:5px solid #10B981; box-shadow:0 0 14px rgba(16,185,129,0.12);">

<h3 style="color:#34D399; margin:0 0 12px 0;">
✅ Explanation
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 10px 0;">
The matrix shape is <b style="color:#FBBF24; font-size:17px;">(3, 3)</b>:
</p>

<ul style="color:#CBD5E1; line-height:1.9; margin:0;">
<li><b style="color:#22D3EE;">3 rows</b> → 3 samples</li>
<li><b style="color:#67E8F9;">3 columns</b> → 3 features</li>
</ul>

<div style="background:#111827; border-left:4px solid #F59E0B; padding:12px 16px; border-radius:8px; margin-top:12px;">
<p style="color:#E2E8F0; margin:0; line-height:1.7;">
📊 This matrix represents the <b style="color:#FBBF24;">complete dataset</b>.
</p>
</div>

</div>

<div style="background:#0F172A; border-left:5px solid #06B6D4; padding:18px 22px; border-radius:12px; box-shadow:0 0 12px rgba(6,182,212,0.12);">

<h3 style="color:#22D3EE; margin:0 0 10px 0;">
🔹 Step 2: Dot Product Calculation
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 8px 0;">
Calculate the <b style="color:#67E8F9;">dot product</b> between one sample
vector and a weight vector.
</p>

<p style="color:#CBD5E1; line-height:1.7; margin:0;">
Then compare the <b style="color:#FBBF24;">manual calculation</b> with the
<b style="color:#34D399;">NumPy result</b>.
</p>

</div>

In [7]:
sample = X[0]

weights = np.array([0.1, 0.0002, 1.5])


manual_result = (
    sample[0] * weights[0] +
    sample[1] * weights[1] +
    sample[2] * weights[2]
)

numpy_result = np.dot(sample, weights)


print("\033[93mManual Dot Product:\033[0m", manual_result)
print("\033[92mNumPy Dot Product:\033[0m", numpy_result)

Manual Dot Product: 17.0
NumPy Dot Product: 17.0


<div style="background:#0F172A; border-left:5px solid #10B981; padding:18px 22px; border-radius:12px; box-shadow:0 0 12px rgba(16,185,129,0.12);">

<h3 style="color:#34D399; margin:0 0 10px 0;">
✅ Explanation
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 10px 0;">
Both calculations should return the <b style="color:#FBBF24;">same value</b>.
</p>

<p style="color:#CBD5E1; line-height:1.7; margin:0;">
This confirms that NumPy's <b style="color:#22D3EE;">dot()</b> performs:
</p>

<div style="background:#111827; border-left:4px solid #06B6D4; padding:12px 16px; border-radius:8px; margin-top:10px;">
<p style="color:#F8FAFC; margin:0; font-weight:bold;">
Feature values × Weights → Sum → <span style="color:#34D399;">Prediction</span>
</p>
</div>

</div>

<div style="background:linear-gradient(135deg,#0F172A,#0C4A6E); padding:20px 24px; border-radius:14px; border-left:5px solid #06B6D4; box-shadow:0 0 14px rgba(6,182,212,0.12); margin-top:18px;">

<h3 style="color:#22D3EE; margin:0 0 10px 0;">
🔹 Step 3: Matrix Multiplication
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0;">
Use <b style="color:#67E8F9;">matrix multiplication</b> to calculate
<b style="color:#F59E0B;">predictions for all samples at once</b>.
</p>

<p style="color:#CBD5E1; line-height:1.7; margin:8px 0 0 0;">
Instead of calculating one sample at a time, the model can process the
<b style="color:#34D399;">whole dataset using one operation</b>.
</p>

</div>

In [8]:
weights = np.array([0.1, 0.0002, 1.5])

predictions = X @ weights


print("\033[94mDataset Matrix:\033[0m")
print(X)

print("\n\033[93mWeights:\033[0m")
print(weights)

print("\n\033[92mPredictions:\033[0m")
print(predictions)

print("\n\033[95mPrediction Shape:\033[0m", predictions.shape)

Dataset Matrix:
[[   25 50000     3]
 [   40 80000    10]
 [   33 62000     5]]

Weights:
[1.0e-01 2.0e-04 1.5e+00]

Predictions:
[17.  35.  23.2]

Prediction Shape: (3,)


<div style="background:linear-gradient(135deg,#0F172A,#0C4A6E); padding:20px 24px; border-radius:14px; border-left:5px solid #10B981; box-shadow:0 0 14px rgba(16,185,129,0.12);">

<h3 style="color:#34D399; margin:0 0 12px 0;">
✅ Explanation
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 10px 0;">
The <b style="color:#22D3EE;">@ operator</b> performs matrix multiplication.
</p>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 8px 0;">
Each row in the dataset is multiplied with the
<b style="color:#FBBF24;">weights vector</b> to produce one prediction.
</p>

<ul style="color:#CBD5E1; line-height:1.9; margin-top:8px;">
<li>👤 <b style="color:#22D3EE;">Sample 1</b> → Prediction 1</li>
<li>👤 <b style="color:#22D3EE;">Sample 2</b> → Prediction 2</li>
<li>👤 <b style="color:#22D3EE;">Sample 3</b> → Prediction 3</li>
</ul>

<div style="background:#111827; border-left:4px solid #F59E0B; padding:12px 16px; border-radius:8px; margin-top:12px;">

<p style="color:#E2E8F0; margin:0; line-height:1.7;">
The output shape <b style="color:#FBBF24; font-size:17px;">(3,)</b>
means we have <b style="color:#34D399;">three predictions</b>.
</p>

</div>

</div>

<div style="background:#0F172A; border-left:5px solid #EF4444; padding:18px 22px; border-radius:12px; box-shadow:0 0 12px rgba(239,68,68,0.12); margin-top:18px;">

<h3 style="color:#F87171; margin:0 0 10px 0;">
🔹 Step 4: Shape Mismatch Error
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0;">
Machine Learning errors often happen because
<b style="color:#FBBF24;">matrix shapes do not match</b>.
</p>

<p style="color:#CBD5E1; line-height:1.7; margin:8px 0 0 0;">
Let's create an <b style="color:#F87171;">incorrect weight vector</b>
and observe the resulting error.
</p>

</div>

In [9]:
wrong_weights = np.array([0.1, 0.0002])

wrong_prediction = X @ wrong_weights

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

<div style="background:#0F172A; border-left:5px solid #EF4444; padding:20px 22px; border-radius:12px; box-shadow:0 0 12px rgba(239,68,68,0.12);">

<h3 style="color:#F87171; margin:0 0 12px 0;">
⚠️ Shape Mismatch Error
</h3>

<p style="color:#CBD5E1; line-height:1.7; margin:0 0 12px 0;">
The error happened because the <b style="color:#F87171;">shapes do not match</b>.
The weight vector contains only <b style="color:#F87171;">2 values</b>,
while the input matrix <b style="color:#22D3EE;">X</b> contains
<b style="color:#34D399;">3 features per sample</b>.
</p>

<div style="background:#111827; border-radius:9px; padding:12px 16px; margin:10px 0;">

<p style="color:#CBD5E1; margin:0; line-height:1.8;">
<b style="color:#67E8F9;">X shape:</b> (3, 3)
<br>
<span style="color:#94A3B8;">→ 3 samples</span>
<br>
<span style="color:#94A3B8;">→ 3 features</span>
<br><br>
<b style="color:#FBBF24;">Weights shape:</b> (2,)
<br>
<span style="color:#94A3B8;">→ Only 2 weights</span>
</p>

</div>

<p style="color:#CBD5E1; line-height:1.7; margin:12px 0 10px 0;">
For matrix multiplication, the number of
<b style="color:#67E8F9;">features must equal the number of weights</b>.
Since <b style="color:#F87171;">3 ≠ 2</b>, NumPy raises a
<b style="color:#F87171;">ValueError</b>.
</p>

<div style="background:#111827; border-left:4px solid #10B981; padding:12px 16px; border-radius:8px;">

<p style="color:#94A3B8; margin:0 0 6px 0;">
✔️ Correct:
</p>

<p style="color:#F8FAFC; font-size:18px; font-weight:bold; margin:0;">
(3, 3) @ (3,) → <span style="color:#34D399;">(3,)</span>
</p>

</div>

</div>